FROM python:3.10

RUN apt-get update 

COPY . /usr/src/app

WORKDIR /usr/src/app/frontend

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -U kaleido
EXPOSE 8501

CMD streamlit run app.py
